# Generated by Django 5.2.11 on 2026-02-10 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('min_spots', models.PositiveSmallIntegerField(default=0)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed amount per spot'), ('percent', 'Percentage off')], default='fixed', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=150, max_digits=8)),
                ('spot_type', models.CharField(blank=True, max_length=100)),
                ('max_slots', models.PositiveSmallIntegerField(default=1)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='bookings.show')),
            ],
            options={
                'ordering': ['show__date', 'time'],
                'unique_together': {('show', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.coupon')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.spot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
