# Generated by Django 5.2.11 on 2026-03-27 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_booking_status_alter_booking_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('pre_booking', 'Pre-Booking'), ('create_order', 'Create Order'), ('verify_payment', 'Verify Payment'), ('payment_cancelled', 'Payment Cancelled')], max_length=20)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_logs', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Razorpay Log',
                'verbose_name_plural': 'Razorpay Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
