# Generated by Django 5.2.11 on 2026-04-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_razorpaylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='receipt_pdf',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
